### ISSUE TITLE
[BUG] Plan upgrades for Azure SQL Failover group fail or partially complete

### ISSUE THREAD

**Issue by claassen** [cloudfoundry-incubator/csb-brokerpak-azure#20]
**Describe the bug**
When upgrading Azure SQL failover group service instance plans we noticed 2 cases where things do not complete as expected:

1. Upgrading from Basic tier plan to Standard tier plan always fails with error:

Error: waiting for creation of MsSql Database "csb-fog-db-5d4a9d17-2252-4561-b800-7c7817503682" (MsSql Server Name "azugessqlprod" / Resource Group "MFC-CAC-PCF-PSB"): Code="SourceDatabaseEditionCouldNotBeUpgraded" Message="The source database
           'azugessqlprod.csb-fog-db-5d4a9d17-2252-4561-b800-7c7817503682' cannot have higher edition than the target database 'azugessqlprodcae.csb-fog-db-5d4a9d17-2252-4561-b800-7c7817503682'. Upgrade the edition on the target before upgrading source."  on main.tf line
           15, in resource "azurerm_mssql_database" "primary_db":  15: resource "azurerm_mssql_database" "primary_db" { exit status 1

2. Upgrading within the same tier plan completes successfully, and updates the primary database instance, but does not update the secondary database instance.

**To Reproduce**
1. cf create-service csb-azure-mssql-db-failover-group Basic basic-db
2. cf update-service basic-db -p StandardS0

1. cf create-service csb-azure-mssql-db-failover-group StandardS0 standard-db
2. cf update-service standard-db -p StandardS1
3. Verify in Azure that both databases have been updated

**Expected behavior**
Plans updates should complete successfully and both databases in the failover group should be updated to the specified plan in Azure.

**Additional context**
BROKER_VERSION=0.2.3
BROKERPAK_VERSION=1.0.0-rc.38

According to Microsoft, when upgrading the service plan for databases in failover groups, the secondary database should be upgraded first, followed by the primary database. Possible the broker is not following this order leading to these issues. 

For the case where the update fails completely when upgrading from Basic to Standard tier plan, we were able to successfully update the plans directly in Azure afterwords by updating the secondary DB first.

**Comment by claassen** [comment]
Some more information:

If I create a new FOG DB service instance and try to update the plan, it will only update the plan for the primary DB in Azure. If I then manually update the plan for the secondary DB to match, and then create a new subsume instance for the existing DB, a subsequent plan update works successfully and updates the plans for both DBs in Azure.

**Comment by erniebilling** [comment]
I'm not sure how this could be accomplished in terraform - during creation, the primary has to be created first, then the secondary is created referencing the primary. During update, that order would have to be reversed which seems impossible.

Also, be careful updating across sku families, they are destructive in some cases.

We'll do some investigation and see how this can be improved.

**Comment by aristosvo** [comment]
@erniebilling A similar mechanism is implemented in Terraform for Postgres [here](https://github.com/terraform-providers/terraform-provider-azurerm/pull/10754)

**Comment by erniebilling** [comment]
I don't see any way to make this work in terraform. The problem only occurs when you try to upgrade across DTU families (basic to standard for instance.) If I try to make the secondary database depend on the primary (so it updates first) terraform fails with a circular dependency. Best option at this point is to only offer plans within the same family, so upgrades can function. Other option would be for azurerm provider to be aware of what is going on and do things in the right order, but I'm not sure if that is possible.

**Comment by aristosvo** [comment]
@erniebilling the easiest way to fix this would be to implement it in the azure terraform provider. As mentioned before, I've implemented a similar pattern for Postgres!

Please file an issue like [this one](https://github.com/terraform-providers/terraform-provider-azurerm/issues/10284), I am interested in fixing it.

**Comment by claassen** [comment]
@erniebilling Even plan updates within the same family don't work as expected though, it only updates the primary DB.

**Comment by erniebilling** [comment]
@claassen a bug in the azurerm provider prevented updating the secondary db size, it looks like it has been fixed and will be included in the next release.

**Comment by aristosvo** [comment]
Thanks @blgm!

**Comment by alex-tw-lam** [comment]
@blgm are the azure provider 2.57, and the other changes merged?

**Comment by blgm** [comment]
Hi @alex-tw-lam, they are not yet.

**Comment by claassen** [comment]
Still seeing issues upgrading from Basic to Standard tier with the latest release (1.0.0-rc39):

```
status:    update failed
message:   Error: waiting for creation of MsSql Database "csb-fog-db-bf834bab-cca9-4c3d-bcc6-1370cd561773" (MsSql Server Name "azugessqlsandbox" / Resource Group "MFC-USE-PCF-PSB"): Code="SourceDatabaseEditionCouldNotBeUpgraded" Message="The source database
           'azugessqlsandbox.csb-fog-db-bf834bab-cca9-4c3d-bcc6-1370cd561773' cannot have higher edition than the target database 'azugessqlsandboxdr.csb-fog-db-bf834bab-cca9-4c3d-bcc6-1370cd561773'. Upgrade the edition on the target before upgrading source."  on main.tf
           line 15, in resource "azurerm_mssql_database" "primary_db":  15: resource "azurerm_mssql_database" "primary_db" { exit status 1
```

**Comment by aristosvo** [comment]
Yeah, tested that as well and didn't implement the solution yet, as it's not clear whether Azure supports it: https://docs.microsoft.com/en-us/azure/azure-sql/database/active-geo-replication-overview#upgrading-or-downgrading-primary-database.

If you have a working example how to do it with `az cli`, I might spend some time on implementing it.

**Comment by claassen** [comment]
@aristosvo I'm not familiar with the internal workings of Terraform to know if how feasible this is or not, but it seems like the solution should be as simple as just ensuring the secondary DB is updated before the primary. Our workaround has been to manually update the secondary DB in Azure, followed by the primary in order to do plan updates across tiers.

**Comment by claassen** [comment]
Actually I'm wondering if this may be as simple as configuring the dependencies in the Terraform the broker uses to ensure that the primary DB resource depends on the secondary DB resource so that changes are made to the secondary first. I can try experimenting with this.

**Comment by aristosvo** [comment]
Okay, looks like I have a solution here, but I need to test this extensively as this may contain a few edge cases.

I'm especially not experienced with elastic pools, so if you have experience scaling from single database to pools in FOG, let me know.

**Comment by blgm** [comment]
I've created a new issue #47 to continue the conversation since this issue was closed.
